cabal-version:       3.0
name:                advent-of-code2024
version:             0.1.0.0
-- synopsis:
-- description:
author:              quilty128
maintainer:          quilty.holly@gmail.com
build-type:          Simple
extra-source-files:  README.md

common common-options
  default-language: Haskell2010
  ghc-options: -Wall -fobject-code
  hs-source-dirs: src
  build-depends:
      base ^>=4.18 && <5
    , vector
    , matrix
    , hashmap
    , sized-vector

library
  import: common-options
  exposed-modules:
    Shared.VectorHelper
    , Shared.MatrixHelper
    , Shared.Utils

executable day1
  import: common-options
  main-is: Day1/Main.hs
  hs-source-dirs: src

executable day2
  import: common-options
  main-is: Day2/Main.hs
  hs-source-dirs: src

executable day3
  import: common-options
  main-is: Day3/Main.hs
  hs-source-dirs: src

executable day4
  import: common-options
  main-is: Day4/Main.hs
  hs-source-dirs: src
  other-modules:
    Shared.VectorHelper
    , Shared.MatrixHelper

executable day5
  import: common-options
  main-is: Day5/Main.hs
  hs-source-dirs: src
  other-modules:
    Shared.Utils

executable day6
  import: common-options
  main-is: Day6/Main.hs
  hs-source-dirs: src

executable day7
  import: common-options
  main-is: Day7/Main.hs
  hs-source-dirs: src
  other-modules:
    Day7.Part1
    Day7.Part2

executable day7-optimized
  import: common-options
  main-is: Day7Optimized/Main.hs
  hs-source-dirs: src
  other-modules:
    Day7Optimized.Part1
    , Day7Optimized.Part2

executable day8
  import: common-options
  main-is: Day8/Main.hs
  hs-source-dirs: src
  other-modules:
    Day8.Part1
    Day8.Part2

executable day9
  import: common-options
  main-is: Day9/Main.hs
  hs-source-dirs: src
